spring:
  application:
    name: CareerSim
  profiles:
    active: dev

  datasource:

    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC

    username: root
    password: ${MYSQL_ROOT_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration      # ← ADICIONA
    validate-on-migrate: false            # ← ADICIONA (temporário)
    out-of-order: true                    # ← ADICIONA (temporário)

  # ← ADICIONA ESSA SEÇÃO INTEIRA
  logging:
    level:
      org.flywaydb: DEBUG